### ISSUE TITLE
 'ascii' codec can't encode characters in position 383-384

### ISSUE THREAD

**Issue by bemoregt** [koallen/google-image-downloader#3]
Hi, @koallen 

I have met this error

```Python
File "download_images.py", line 77, in <module>
    soup = BeautifulSoup(str(source), "html.parser")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 383-384: ordinal not in range(128)
```

What's wrong with me?

Thanks in advances.

**Comment by koallen** [comment]
Hi, please make sure

- You are using Python 3
- Your terminal's locale is UTF-8 ([refer to here on how to set it up](https://stackoverflow.com/questions/27591015/python-ascii-codec-cant-encode-characters))

Let me know if this resolves your issue.

**Comment by bemoregt** [comment]
Thanks I will try this. 

나의 iPhone에서 보냄

2017. 7. 3. 오전 8:59 Siyuan Liu <notifications@github.com> 작성:

**Comment by koallen** [comment]
Is this fixed? If so, I will close this issue.

**Comment by bemoregt** [comment]
Excellent Works ~!!

Many Thanks ~

**Comment by koallen** [comment]
Ok closing.
