### ISSUE TITLE
chrome scrolling OK, making directory OK, but nothing is in it.

### ISSUE THREAD

**Issue by bemoregt** [koallen/google-image-downloader#4]
Hi, @koallen @SkyrisBactera 

The ChromeBrowser works..
scrolling OK, making directory OK, but nothing is in it.

My Dogs directory is void.

What's wrong with me?

Thanks in advance ~

**Comment by koallen** [comment]
Were there any error messages? I haven't worked on this project for quite a long time, maybe the parsing is no longer effective.

**Comment by bemoregt** [comment]
Hi, @koallen @SkyrisBactera 

My Error is here
---------------------
python3 download_images.py dog
Bus error: 10
---------------------

What's wrong with me?

Thanks.

**Comment by koallen** [comment]
- Please don't at SkyrisBactera, he's not part of the project.
- You used the wrong syntax for code blocks, I corrected it

I will take a look when I have time.

**Comment by bemoregt** [comment]
Thanks in advance~

나의 iPhone에서 보냄

2017. 7. 6. 오후 10:21 Siyuan Liu <notifications@github.com> 작성:

**Comment by koallen** [comment]
I fixed the issue with the latest commit, please look at the new usage section on readme

**Comment by bemoregt** [comment]
Thanks a Lot ~


수고하세요.
